### ISSUE TITLE
All modes besides default parse YAML metadata as HTML

### ISSUE THREAD

**Issue by adriaandens** [mkende/pmarkdown#4]
```perl
my $m_cmark = Markdown::Perl->new(mode => "cmark"); # Also for github, markdown mode but not for "default"
my $result = $m_cmark->convert("---\nname: Index\n---\n# Header");
print $result;
```
prints 
```
<hr />
<h2>name: Index</h2>
<h1>Header</h1>
```
**expected**: All Markdown modes ignore the YAML for generating the HTML output.
```
<h1>Header</h1>
```

**Comment by mkende** [comment]
In cmark and github modes, I’m trying to keep a close compatibility with the behavior of these tools (while "default" uses my preferred set of syntax). And you can see on [this babelmark example](https://babelmark.github.io/?text=---%0Aname%3A+Index%0A---%0A%23+Header) that most tools will not parse the YAML header.

If you want github mode (for example) with YAML metadata support, you can always pass the `parse_file_metadata` option in addition to the mode that you’re using.

```
$ echo -e "---\nname: Index\n---\n# Header" | pmarkdown --mode cmark --option parse_file_metadata=yaml
<h1>Header</h1>
```

Would that work for you?

**Comment by adriaandens** [comment]
Yeah that works.
```perl
my %options = (parse_file_metadata => 'yaml');
my $m_cmark = Markdown::Perl->new(mode => "cmark");
$m_cmark->set_options(%options);
my $result = $m_cmark->convert("---\nname: Index\n---\n# Header");
print $result;
```
prints (only) the expected Header as h1 element. It was not obvious from reading the [docs](https://metacpan.org/pod/Markdown::Perl::Options) that `parse_file_metadata` changes its internal value depending on the mode, as "yaml" is indicated as default.
